export enum FiltroPesquisaFuncionalidade {
  CONSULTAR_ENCARGO_MENSAL = "ConsultarEncargoMensal.Manter",
  CONSULTAR_FATOR_EUST_ANEEL = "ConsultarFatorEustAneel.Manter",
  CONSULTAR_RATEIO_EUSTFR = "ConsultarRateioEUSTFR.Manter",
  DESCONTO_TUST_TIPO_EMPREENDIMENTO = "DescontoTustTipoEmpreendimento.Manter",
  ENCARGOS_TUSDG = "EncargoTUSDg.Manter",
  ENCARGOS_COTA_PARTE_ITAIPU = "EncargosCotaParteItaipu.Manter",
  DESCONTO_TUST_EMPREENDIMENTO = "DescontoTustEmpreendimento.Manter",
  CONSULTAR_DESCONTO_TUST_CCEE = "ConsultarDescontoTustCCEE.Manter",

  RESUMO_COMPARACAO_PERIODO_ALERTAS = "ResumoComparacaoPeriodoAlertas",
  RESUMO_COMPARACAO_PERIODO_ENCARGO_PERMANENTE_GE_DETALHAR = "ResumoComparacaoPeriodoEncargoPermanenteGE.Detalhar",
  RESUMO_COMPARACAO_PERIODO_ENCARGO_PERMANENTE_CLDT_DETALHAR = "ResumoComparacaoPeriodoEncargoPermanenteCLDT.Detalhar",
  RESUMO_COMPARACAO_PERIODO_TUSDG_DETALHAR = "ResumoComparacaoPeriodoTUSDg.Detalhar",
  RESUMO_COMPARACAO_PERIODO_RATEIO_DETALHAR = "ResumoComparacaoPeriodoRateio.Detalhar",
  RESUMO_COMPARACAO_PERIODO_ITAIPU_DETALHAR = "ResumoComparacaoPeriodoItaipu.Detalhar",
  RESUMO_COMPARACAO_PERIODO_SETORIAL = "ResumoComparacaoPeriodoSetorial.Detalhar",
  RESUMO_COMPARACAO_PERIODO_IMPORTACAO_EXPORTACAO = "ResumoComparacaoPeriodoImportacaoExportacao.Detalhar",


  AGENTE_APURACAO_CONSULTAR = "AgenteApuracao.Consultar",

  PAINEL_VALIDACAO_AGENTE_ENCARGO_PERMANENTE_GE_MANTER = "PainelValidacaoAgenteEncargoPermanenteGE.Manter",
  PAINEL_VALIDACAO_AGENTE_ENCARGO_PERMANENTE_CLDT_MANTER = "PainelValidacaoAgenteEncargoPermanenteCLDT.Manter",
  PAINEL_VALIDACAO_AGENTE_TUSDG_MANTER = "PainelValidacaoAgenteTUSDg.Manter",
  PAINEL_VALIDACAO_AGENTE_RATEIO_MANTER = "PainelValidacaoAgenteRateio.Manter",
  PAINEL_VALIDACAO_AGENTE_ITAIPU_MANTER = "PainelValidacaoAgenteItaipu.Manter",

  REDE_BASICA_CL_DETALHAR = "RedeBasicaCL.Detalhar",
  REDE_BASICA_GE_DETALHAR = "RedeBasicaGE.Detalhar",
  REDE_BASICA_RETROATIVA_GE_DETALHAR = "RedeBasicaRetroativaGE.Detalhar",
  REDE_BASICA_RETROATIVA_CL_DETALHAR = "RedeBasicaRetroativaCL.Detalhar",
  REDE_FRONTEIRA_CLDT_DETALHAR = "RedeFronteiraCLDT.Detalhar",
  REDE_FRONTEIRA_RETROATIVA_CLDT_DETALHAR = "RedeFronteiraRetroativaCLDT.Detalhar",
  REDE_BASICA_SOBRECONTRATACAO_DETALHAR = "RedeBasicaSobrecontratacao.Detalhar",
  REDE_BASICA_ULTRAPASSAGEM_GE_DETALHAR = "RedeBasicaUltrapassagemGE.Detalhar",
  REDE_BASICA_ULTRAPASSAGEM_CL_DETALHAR = "edeBasicaUltrapassagemCL.Detalhar",
  REDE_BASICA_ULTRAPASSAGEM_DT_DETALHAR = "RedeBasicaUltrapassagemDT.Detalhar",
  REDE_FRONTEIRA_ULTRAPASSAGEM_DT_DETALHAR = "RedeFronteiraUltrapassagemCL.Detalhar",
  REDE_FRONTEIRA_ULTRAPASSAGEM_CL_DETALHAR = "RedeFronteiraUltrapassagemDT.Detalhar",
  REDE_BASICA_DT_DETALHAR = "RedeBasicaDT.Detalhar",
  REDE_BASICA_RETROATIVA_DT_DETALHAR = "RedeBasicaRetroativaDT.Detalhar",
  REDE_BASICA_ENCARGO_ADICIONAL = "RedeBasicaEncargoAdicional.Detalhar",

  CONSULTAR_ENCARGOS_SETORIAIS_CCEE = "EncargosSetoriaisCCEE.Consultar",
  CONSULTAR_ENCARGOS_SETORIAIS_CCEE_ATUALIZAR_TARIFA_CDE = "EncargosSetoriaisCCEE.Atualizar_Tarifa_CDE",
  CONSULTAR_ENCARGOS_SETORIAIS_CCEE_ATUALIZAR_TARIFA_PROINFA = "EncargosSetoriaisCCEE.Atualizar_Tarifa_PROINFA",
  CONSULTAR_ENCARGOS_SETORIAIS_CCEE_ATUALIZAR_TARIFA_TUSTIMP = "EncargosSetoriaisCCEE.Atualizar_Tarifa_TUSTIMP",
  CONSULTAR_ENCARGOS_SETORIAIS_CCEE_ATUALIZAR_TARIFA_TUII = "EncargosSetoriaisCCEE.Atualizar_Tarifa_TUII",
}
